In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [3]:
df['satisfaction_level'] = df['pclass'].map({1: 'high', 2:'medium', 3:'low'})
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,satisfaction_level
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,low
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,high
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,low
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,high
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,low

In [4]:
df.isna().sum()

survived                0
pclass                  0
sex                     0
age                   177
sibsp                   0
parch                   0
fare                    0
embarked                2
class                   0
who                     0
adult_male              0
deck                  688
embark_town             2
alive                   0
alone                   0
satisfaction_level      0
dtype: int64

In [5]:
df = df.drop('deck', axis=1)
df['age']= df['age'].fillna(df['age'].median())

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone,satisfaction_level
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False,low
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False,high
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True,low
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False,high
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True,low

In [6]:
df.isna().sum()

survived              0
pclass                0
sex                   0
age                   0
sibsp                 0
parch                 0
fare                  0
embarked              2
class                 0
who                   0
adult_male            0
embark_town           2
alive                 0
alone                 0
satisfaction_level    0
dtype: int64

In [7]:
df.dropna()
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone,satisfaction_level
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False,low
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False,high
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True,low
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False,high
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True,low

In [8]:
df.shape

(891, 15)

In [9]:
from sklearn.model_selection import train_test_split

x= df[['satisfaction_level']]
y = df[['alive']]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [10]:
print(x_train.shape)
print(x_test.shape)

(712, 1)
(179, 1)

In [11]:
print(x_train.head())
type(x_train)

    satisfaction_level
331               high
733             medium
382                low
704                low
813                low

pandas.core.frame.DataFrame

In [12]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[['low', 'medium', 'high']])

x_train_encoded = oe.fit_transform(x_train)
x_test_encoded = oe.transform(x_test)

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_train_encoded = le.fit_transform(y_train.values.ravel())
y_test_encoded = le.fit_transform(y_test.values.ravel())

In [29]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone,satisfaction_level
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False,low
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False,high
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True,low
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False,high
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True,low

In [30]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
trf1 = ColumnTransformer([
    "one_sex_embarked", OneHotEncoder(sparse_output=False, handle_unknown = 'ignore'), [2, 7]
], remainder = 'passthrough')

In [33]:
from sklearn.preprocessing import MinMaxScaler

trf2 = ColumnTransformer([
    'scaled', MinMaxScaler(), [3,6]
], remainder = 'passthrough')

In [ ]:
trf3 =